apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: jvm-build-suite-component-ojlc
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/ysubrama_org/jvm-build-oosl-tenant/jvm-build-suite-application-hjvq/jvm-build-suite-component-ojlc@sha256:0eb53aa9427fcab037f3cbbdea280b1a4d621a148699b61ed47134fff0c7a591
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
