apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: jvm-build-suite-component-ojlc
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: jvm-build-suite-component-ojlc
    app.kubernetes.io/part-of: jvm-build-suite-application-hjvq
  name: jvm-build-suite-component-ojlc
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: jvm-build-suite-component-ojlc
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: jvm-build-suite-component-ojlc
    spec:
      containers:
      - image: quay.io/ysubrama_org/jvm-build-oosl-tenant/jvm-build-suite-application-hjvq/jvm-build-suite-component-ojlc@sha256:0eb53aa9427fcab037f3cbbdea280b1a4d621a148699b61ed47134fff0c7a591
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
